package EjerciciosProyectoFinal;

public enum EstadosDeMexico {
    AGUASCALIENTES, BAJA_CALIFORNIA,BAJA_CALIFORNIA_SUR,CAMPECHE, CHIAPAS,
    CHIHUAHUA,CIUDAD_DE_MEXICO,COAHUILA,COLIMA,DURANGO,GUANAJUATO,GUERRERO,HIDALGO,
    JALISCO,MEXICO,MICHOACAN,MORELOS,NAYARIT,NUEVO_LEON,OAXACA,PUEBLA,QUERETARO,QUINTANA_ROO,SAN_LUIS_POTOSI,
    SINALOA,SONORA,TABASCO,TAMAULIPAS,TLAXCALA,VERACRUZ,YUCATAN,ZACATECAS
    }
